export default {
	images : [
		"my-wedding/gallery/0.jpg",
		"my-wedding/gallery/1.jpg",
		"my-wedding/gallery/2.jpg",
		"my-wedding/gallery/3.jpg",
		"my-wedding/gallery/4.jpg",
		"my-wedding/gallery/5.jpg",
		"my-wedding/gallery/6.jpg",
		"my-wedding/gallery/7.jpg",
		"my-wedding/gallery/8.jpg",
		"my-wedding/gallery/9.jpg",
		"my-wedding/gallery/10.jpg",
		"my-wedding/gallery/11.jpg",
		"my-wedding/gallery/12.jpg",
		"my-wedding/gallery/13.jpg",
		"my-wedding/gallery/14.jpg",
		"my-wedding/gallery/15.jpg",
		"my-wedding/gallery/16.jpg",
		"my-wedding/gallery/17.jpg",
		"my-wedding/gallery/18.jpg",
		"my-wedding/gallery/19.jpg",
		"my-wedding/gallery/20.jpg",
		"my-wedding/gallery/21.jpg",
		"my-wedding/gallery/22.jpg",
		"my-wedding/gallery/23.jpg",
		"my-wedding/gallery/24.jpg",
	]

}